commonLabel: nginx

namespace:
  name: dev

deployment:
  name: nginx-deployment
  replicas: 2
  container:
    name: nginx
    port: 80
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

service:
  name: nginx-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: nginx-ingress
  className: nginx
  host: panchanandevops.com
