apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    name: kind
  project: default
  sources:
  # Chart from Chart Repo
  - chart: hello-world
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
    helm:
      valueFiles:
      - $values/multi-env-helm-chart/values-prod.yaml
  # Values from Git
  - repoURL: 'https://github.com/panchanandevops/argocd-helm.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
